name: CI (Optimized)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUSTFLAGS: "-D warnings -C link-arg=-fuse-ld=lld"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  # Quick checks that can fail fast
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-

    - name: Check Cargo.lock
      run: cargo update --locked --package mcp-helper

  # Main test job - runs on multiple platforms
  test:
    name: Test - ${{ matrix.os }} / ${{ matrix.rust }}
    needs: quick-checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        include:
          # Test on minimum supported Rust version
          - os: ubuntu-latest
            rust: "1.78.0"  # Updated MSRV to support lock file v4

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    # Use sccache for compilation caching
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    # Better Rust caching
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.os }}-${{ matrix.rust }}
        cache-all-crates: true
        cache-on-failure: true
        cache-directories: |
          ~/.cargo/bin/
          target/

    - name: Build
      run: cargo build --all-targets
      env:
        RUSTC_WRAPPER: "sccache"

    - name: Run tests
      run: cargo test --all
      env:
        RUSTC_WRAPPER: "sccache"

    - name: Run linter
      if: matrix.rust == 'stable'
      run: cargo clippy -- -D warnings

  # Comprehensive CI job with coverage
  ci-full:
    name: Full CI Suite
    needs: quick-checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lld

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
        cache-on-failure: true

    # Use cargo-binstall for faster tool installation
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install CI tools
      run: |
        cargo binstall --no-confirm --force cargo-audit cargo-tarpaulin

    - name: Check formatting
      run: make fmt-check

    - name: Run linter
      run: make lint
      env:
        RUSTC_WRAPPER: "sccache"

    - name: Build
      run: make build
      env:
        RUSTC_WRAPPER: "sccache"

    - name: Run tests
      run: make test
      env:
        RUSTC_WRAPPER: "sccache"

    - name: Run security audit
      run: make audit

    - name: Generate coverage
      run: make coverage-ci
      env:
        RUSTC_WRAPPER: ""  # Disable sccache for tarpaulin

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: tarpaulin-report.html
        retention-days: 7

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./tarpaulin-report.html
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

  # Build release binaries in parallel
  release-build:
    name: Release Build - ${{ matrix.target }}
    needs: quick-checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: false
            
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false
            
          - os: macos-latest
            target: x86_64-apple-darwin
            use_cross: false
            
          - os: macos-latest
            target: aarch64-apple-darwin
            use_cross: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}
        cache-all-crates: true

    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
      env:
        RUSTC_WRAPPER: "sccache"

    - name: Create archive (Unix)
      if: runner.os != 'Windows'
      run: |
        cd target/${{ matrix.target }}/release
        tar czf ../../../mcp-helper-${{ matrix.target }}.tar.gz mcp-helper
        cd ../../../

    - name: Create archive (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../mcp-helper-${{ matrix.target }}.zip mcp-helper.exe
        cd ../../../

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcp-helper-${{ matrix.target }}
        path: mcp-helper-${{ matrix.target }}.*
        retention-days: 7

  # Create release when pushing a version tag
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, ci-full, release-build]
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: mcp-helper-*
        merge-multiple: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mcp-helper-*.tar.gz
          mcp-helper-*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}